[google]
spreadsheet_id = "REMPLACEZ_PAR_L_IDENTIFIANT_DU_GOOGLE_SHEETS"

[gcp_service_account]
type = "service_account"
project_id = "votre-projet-google-cloud"
private_key_id = "REMPLACEZ_MOI"
private_key = "-----BEGIN PRIVATE KEY-----\nREMPLACEZ_MOI\n-----END PRIVATE KEY-----\n"
client_email = "compte-service@votre-projet-google-cloud.iam.gserviceaccount.com"
client_id = "REMPLACEZ_MOI"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "REMPLACEZ_MOI"
universe_domain = "googleapis.com"
